paths:
  /admin/product/:                # path of the product from your endpoint
    post:                 # endpoint request type (post request)
      tags:               # Tag property
        - Products            # Value of the tag
      summary: creates a new Product
      produces:
      - application/json
      parameters:         # request parameters
      - in: body          # request body
        name: create Product     # name of request, can be any name
        description: It enables a product to create an Product
        required: false   # can also be true depending on product preference
        schema:           # Schema definition
          $ref: '#/definitions/createCat' 
      responses:          # server responses
        201:
          description: An object with product details
          schema:           # Schema definition
            $ref: '#/definitions/createCat'
    get:                 # endpoint request type (post request)
      tags:               # Tag property
        - Products            # Value of the tag
      summary: Get All List Products
      responses:          # server responses
        201:
          description: An object with product details
  /admin/product/:id:
    get:                 # endpoint request type (post request)
      tags:               # Tag property
        - Products            # Value of the tag
      summary: Get Detail Products
      produces:
      - application/json
      parameters:
      - name: id      # name of parameter passed
        in: path      # parameters in the path
        description: Path Parameter Products ID
        required: true
        type: string
      responses:          # server responses
        201:
          description: An object with product details
    put:
      tags:
        - Products
      summary: Update Product Data
      produces:
      - application/json
      parameters:
      - name: id      # name of parameter passed
        in: path      # parameters in the path
        description: Path Parameter Products ID
        required: true
        type: string
      - in: body
        name: update
        description: Product Update basic Data
        required: false
        schema:
          $ref: '#/definitions/updateCat'
    delete:
      tags:
        - Products
      summary: Delete Product Data Permanently
      produces:
      - application/json
      parameters:
      - name: id      # name of parameter passed
        in: path      # parameters in the path
        description: path parameter takes the Product id
        required: true
        type: string
definitions:        # Schema defination for request body
  createCat:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      status:
        type: number
  updateCat:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      status:
        type: number